# Generated by Django 6.0.2 on 2026-08-14 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modelo_afectado', models.CharField(blank=True, default='', max_length=100)),
                ('registro_id', models.BigIntegerField(blank=True, null=True)),
                ('detalles_cambio', models.JSONField(blank=True, default=dict)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_sistema',
            },
        ),
    ]
