# Generated by Django 6.0.2 on 2026-08-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alumnos')),
                ('nombres', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=255)),
                ('curp', models.CharField(db_index=True, max_length=18)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, default='', max_length=1)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='CalificacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_ordinaria', models.FloatField(blank=True, null=True)),
                ('extraordinario_1', models.FloatField(blank=True, null=True)),
                ('extraordinario_2', models.FloatField(blank=True, null=True)),
                ('calificacion_final', models.FloatField(blank=True, null=True)),
                ('calificacion_letra', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'db_table': 'calificaciones_detalle',
            },
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_inicio', models.IntegerField(blank=True, null=True)),
                ('anio_fin', models.IntegerField(blank=True, null=True)),
                ('clave', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'db_table': 'ciclos_escolares',
            },
        ),
        migrations.CreateModel(
            name='InscripcionPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_periodo', models.FloatField(blank=True, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('INSCRITO', 'Inscrito'), ('CURSANDO', 'Cursando'), ('BAJA', 'Baja'), ('CONCLUIDO', 'Concluido'), ('SUSPENDIDO', 'Suspendido')], default='CURSANDO', max_length=30)),
                ('es_actual', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inscripciones_periodo',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_numero', models.IntegerField()),
                ('clave_materia', models.CharField(max_length=50)),
                ('nombre_materia', models.CharField(max_length=255)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'catalogo_materias',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, default='', max_length=20)),
                ('numero', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodos_academicos',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_plan', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('creditos_totales', models.IntegerField(blank=True, null=True)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planes_estudio',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('duracion_meses', models.PositiveSmallIntegerField()),
                ('ciclos_por_anio', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Tipo de periodo',
                'verbose_name_plural': 'Tipos de periodo',
                'db_table': 'tipos_periodo',
            },
        ),
        migrations.CreateModel(
            name='TrayectoriaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('creditos_acumulados', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('nivel_actual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_actual', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'trayectoria_academica',
            },
        ),
    ]
