# Generated by Django 6.0.2 on 2026-08-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uh_academico', '0001_initial'),
        ('uh_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='uh_core.datoscontacto'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='domicilio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='uh_core.domicilio'),
        ),
        migrations.AlterUniqueTogether(
            name='cicloescolar',
            unique_together={('anio_inicio', 'anio_fin')},
        ),
        migrations.AddField(
            model_name='calificaciondetalle',
            name='inscripcion_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='uh_academico.inscripcionperiodo'),
        ),
        migrations.AddField(
            model_name='calificaciondetalle',
            name='catalogo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='uh_academico.materia'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='ciclo_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='uh_academico.cicloescolar'),
        ),
        migrations.AddField(
            model_name='inscripcionperiodo',
            name='periodo_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_periodo', to='uh_academico.periodoacademico'),
        ),
        migrations.AddField(
            model_name='planestudio',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='uh_core.carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='plan_estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias', to='uh_academico.planestudio'),
        ),
        migrations.AddField(
            model_name='periodoacademico',
            name='tipo_periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='uh_academico.tipoperiodo'),
        ),
        migrations.AddField(
            model_name='trayectoriaacademica',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trayectorias', to='uh_academico.alumno'),
        ),
        migrations.AddField(
            model_name='trayectoriaacademica',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trayectorias', to='uh_core.carrera'),
        ),
        migrations.AddField(
            model_name='trayectoriaacademica',
            name='estatus_academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trayectorias', to='uh_core.estatusacademico'),
        ),
        migrations.AddField(
            model_name='inscripcionperiodo',
            name='trayectoria_academica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_periodo', to='uh_academico.trayectoriaacademica'),
        ),
        migrations.AlterUniqueTogether(
            name='calificaciondetalle',
            unique_together={('inscripcion_periodo', 'catalogo_materia')},
        ),
        migrations.AlterUniqueTogether(
            name='planestudio',
            unique_together={('carrera', 'clave_plan', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('plan_estudio', 'clave_materia')},
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('ciclo_escolar', 'tipo_periodo', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionperiodo',
            unique_together={('trayectoria_academica', 'periodo_academico')},
        ),
    ]
