# Generated by Django 6.0.2 on 2026-08-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayectoriaacademica',
            name='titulacion_en_proceso',
            field=models.BooleanField(default=False),
        ),
    ]
