# Generated by Django 6.0.2 on 2026-08-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_academico', '0003_trayectoriaacademica_titulacion_en_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciondetalle',
            name='calificacion_letra',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
