# Generated by Django 6.0.2 on 2026-08-22 06:40

from django.db import migrations


def fix_tipo_periodo(apps, schema_editor):
    TipoPeriodo = apps.get_model("uh_academico", "TipoPeriodo")
    PeriodoAcademico = apps.get_model("uh_academico", "PeriodoAcademico")
    InscripcionPeriodo = apps.get_model("uh_academico", "InscripcionPeriodo")
    Carrera = apps.get_model("uh_core", "Carrera")

    semestral = TipoPeriodo.objects.filter(nombre="Semestral").first()
    semestral_upper = TipoPeriodo.objects.filter(nombre="SEMESTRAL").first()

    if not semestral or not semestral_upper:
        return

    Carrera.objects.filter(tipo_periodo=semestral).update(tipo_periodo=semestral_upper)

    for periodo in PeriodoAcademico.objects.filter(tipo_periodo=semestral):
        conflicto = PeriodoAcademico.objects.filter(
            ciclo_escolar=periodo.ciclo_escolar,
            tipo_periodo=semestral_upper,
            numero=periodo.numero,
        ).first()
        if conflicto:
            for inscripcion in InscripcionPeriodo.objects.filter(periodo_academico=periodo):
                existe = InscripcionPeriodo.objects.filter(
                    trayectoria_academica=inscripcion.trayectoria_academica,
                    periodo_academico=conflicto,
                ).exists()
                if existe:
                    inscripcion.delete()
                else:
                    inscripcion.periodo_academico = conflicto
                    inscripcion.save()
            periodo.delete()
        else:
            periodo.tipo_periodo = semestral_upper
            periodo.save()

    semestral.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('uh_academico', '0004_alter_calificaciondetalle_calificacion_letra'),
    ]

    operations = [
        migrations.RunPython(fix_tipo_periodo, reverse_code=migrations.RunPython.noop),
    ]
