# Generated by Django 6.0.2 on 2026-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_academico', '0005_fix_tipo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoperiodo',
            name='nombre',
            field=models.CharField(choices=[('SEMESTRAL', 'Semestral'), ('CUATRIMESTRAL', 'Cuatrimestral')], max_length=30, unique=True),
        ),
    ]
