# Generated by Django 6.0.2 on 2026-08-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uh_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Colegio Universitario Hispana', max_length=255)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración institucional',
                'verbose_name_plural': 'Configuraciones institucionales',
                'db_table': 'configuracion_institucional',
            },
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('celular', models.CharField(blank=True, default='', max_length=50)),
                ('correo_electronico', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'db_table': 'datos_contacto',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(blank=True, default='', max_length=255)),
                ('numero_exterior', models.CharField(blank=True, default='', max_length=50)),
                ('numero_interior', models.CharField(blank=True, default='', max_length=50)),
                ('colonia', models.CharField(blank=True, default='', max_length=255)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=20)),
                ('municipio', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'domicilios',
            },
        ),
        migrations.CreateModel(
            name='EstatusAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'estatus_academico',
            },
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=20)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('curp', models.CharField(blank=True, default='', max_length=18)),
                ('firma_digital', models.FileField(blank=True, null=True, upload_to='firmas/')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autoridades', to='uh_core.datoscontacto')),
            ],
            options={
                'db_table': 'autoridades',
            },
        ),
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_plantel', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('rgp', models.CharField(blank=True, default='', max_length=100)),
                ('registro_sep', models.CharField(blank=True, default='', max_length=100)),
                ('pagina_web', models.URLField(blank=True, default='')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planteles', to='uh_core.datoscontacto')),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planteles', to='uh_core.domicilio')),
            ],
            options={
                'db_table': 'planteles',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('regimen', models.CharField(blank=True, default='', max_length=30)),
                ('total_ciclos', models.IntegerField(blank=True, null=True)),
                ('acuerdo_sep', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_acuerdo_sep', models.DateField(blank=True, null=True)),
                ('tipo_periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='uh_academico.tipoperiodo')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carreras', to='uh_core.plantel')),
            ],
            options={
                'db_table': 'carreras',
            },
        ),
        migrations.CreateModel(
            name='PlantelAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantel_autoridades', to='uh_core.autoridad')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantel_autoridades', to='uh_core.plantel')),
            ],
            options={
                'db_table': 'plantel_autoridades',
                'unique_together': {('plantel', 'autoridad')},
            },
        ),
    ]
