# Generated by Django 6.0.2 on 2026-08-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='clave',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
