# Generated by Django 6.0.2 on 2026-08-22 06:28

from django.db import migrations


def generate_clave(nombre):
    stopwords = {"LICENCIATURA", "INGENIERIA", "EN", "DE", "Y", "LA", "EL", "LOS", "LAS", "A", "PARA", "CON", "E"}
    words = [w for w in nombre.upper().split() if w not in stopwords]
    abbr = "".join(w[:2] for w in words)
    return (abbr[:5] + "X" * 5)[:5]


def fix_clave_length(apps, schema_editor):
    Carrera = apps.get_model("uh_core", "Carrera")
    used = set()
    for carrera in Carrera.objects.all():
        base = generate_clave(carrera.nombre)
        clave = base
        counter = 1
        while clave in used or Carrera.objects.filter(clave=clave).exclude(pk=carrera.pk).exists():
            clave = f"{base[:4]}{chr(ord('0') + counter)}" if counter < 10 else f"{base[:3]}{counter}"
            counter += 1
        carrera.clave = clave
        carrera.save()
        used.add(clave)


class Migration(migrations.Migration):

    dependencies = [
        ('uh_core', '0003_populate_carrera_clave'),
    ]

    operations = [
        migrations.RunPython(fix_clave_length, reverse_code=migrations.RunPython.noop),
    ]
