# Generated by Django 5.2.16 on 2026-08-31 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uh_core', '0005_improve_carrera_clave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_admin', models.BooleanField(default=False, help_text='Acceso total al sistema (equivalente a staff/admin).')),
                ('puede_dashboard', models.BooleanField(default=False)),
                ('puede_auditoria', models.BooleanField(default=False)),
                ('puede_catalogos', models.BooleanField(default=False)),
                ('puede_emision', models.BooleanField(default=True)),
                ('puede_alumnos', models.BooleanField(default=True)),
                ('puede_calificaciones', models.BooleanField(default=True)),
                ('puede_registros', models.BooleanField(default=True)),
                ('puede_ciclos', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='uh_core.autoridad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='uh_usuarios.rol')),
            ],
            options={
                'db_table': 'perfiles_usuario',
            },
        ),
    ]
