# Generated by Django 5.2.16 on 2026-08-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='permisos_personalizados',
            field=models.JSONField(blank=True, default=dict, help_text='Overrides por usuario. Cada clave es un módulo y el valor (bool) anula el default del rol.'),
        ),
    ]
