# Generated by Django 6.0.2 on 2026-08-14 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uh_academico', '0001_initial'),
        ('uh_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'categorias_documento',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioPolimorfico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_tipo', models.CharField(max_length=20)),
                ('entidad_id', models.IntegerField()),
            ],
            options={
                'db_table': 'destinatarios_polimorficos',
            },
        ),
        migrations.CreateModel(
            name='Externo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('primer_apellido', models.CharField(blank=True, default='', max_length=255)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=255)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='externos', to='uh_core.datoscontacto')),
            ],
            options={
                'db_table': 'externos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('aplica_a', models.CharField(blank=True, default='', max_length=50)),
                ('categoria', models.CharField(choices=[('CONSTANCIAS', 'Constancias'), ('KARDEX', 'Kardex'), ('DIPLOMAS', 'Diplomas'), ('RECONOCIMIENTOS', 'Reconocimientos')], default='CONSTANCIAS', max_length=20)),
                ('plantilla', models.CharField(blank=True, default='pdf/constancias/estudio.html', max_length=255)),
                ('reglas_validacion', models.JSONField(blank=True, default=dict)),
                ('categorias', models.ManyToManyField(blank=True, to='uh_documentos.categoriadocumento')),
            ],
            options={
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('hash_documento', models.CharField(db_index=True, max_length=128)),
                ('snapshot_datos_receptor', models.JSONField(blank=True, default=dict)),
                ('snapshot_academico', models.JSONField(blank=True, default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('html_renderizado', models.TextField(blank=True, default='')),
                ('es_valido', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_academico.alumno')),
                ('autoridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_core.autoridad')),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_documentos.destinatariopolimorfico')),
                ('plantel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_core.plantel')),
                ('externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_documentos.externo')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='uh_documentos.tipodocumento')),
            ],
            options={
                'db_table': 'documentos_emitidos',
            },
        ),
    ]
