# Generated by Django 5.2.16 on 2026-08-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_documentos', '0005_seed_kardex_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='categoria',
            field=models.CharField(choices=[('CONSTANCIAS', 'Constancias'), ('KARDEX', 'Kardex'), ('DIPLOMAS', 'Diplomas'), ('RECONOCIMIENTOS', 'Reconocimientos'), ('TITULO', 'Títulos'), ('DIPLOMAS_RECONOCIMIENTOS', 'Diplomas y Reconocimientos')], default='CONSTANCIAS', max_length=30),
        ),
    ]
