# Generated by Django 5.2.16 on 2026-08-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uh_documentos', '0009_fix_tipos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='categoria',
            field=models.CharField(choices=[('CONSTANCIAS', 'Constancias'), ('KARDEX', 'Kardex'), ('TITULO', 'Títulos'), ('DIPLOMAS_RECONOCIMIENTOS', 'Diplomas y Reconocimientos')], default='CONSTANCIAS', max_length=30),
        ),
    ]
