# Generated by Django 5.2.16 on 2026-09-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uh_documentos', '0010_alter_tipodocumento_categoria'),
        ('uh_documentos', '0010_fix_reglas_validacion'),
    ]

    operations = [
    ]
